### ISSUE TITLE
UX: Edit button not obvious

### ISSUE THREAD

**Issue by gabrc52** [DormSoup/dormsoup#35]
I missed the edit button. It is black, the same as text. It would be nice to make it more prominent, and maybe show your events highlighted somehow so you know it's yours.

And once you click on the event, it shows the email, but there is no edit button there. I believe there should also be an edit button there.

![image](https://github.com/user-attachments/assets/214fd59b-8024-4639-8d4b-fbe92612d8f3)

**Comment by maurayonori** [comment]
Hi there,

I've been trying to help solve the issue regarding the edit button visibility, but I've noticed a potential misalignment. The issue seems to be UI/UX-related, but I'm working with the dormsoup-daemon repository which appears to be solely focused on backend functionality (email parsing, event processing, etc.).

After forking and setting up the project locally, I couldn't find any UI components or frontend code. This makes me wonder: Should this issue be addressed in a different repository that handles the frontend/UX portion of DormSoup?

The current README only contains information about:
- Email processing daemon functionality
- Database setup
- Testing procedures
- Server deployment

Could you please point me to the correct repository for implementing these UI/UX improvements? Or should we consider this as a broader architectural discussion about where UI components should live?

I'm eager to help improve the user experience, but want to make sure I'm working in the right place.

Best regards

**Comment by gabrc52** [comment]
My bad, it was in the wrong repo. I'm curious how you came across this issue.

**Comment by maurayonori** [comment]
I have been considering contributing to OSS, and I decided to take on a 'good first issue' on GitHub as a starting point. I came across an interesting project, and since the changes seemed relatively straightforward, I thought it would be a good opportunity to contribute, which brings me to my current situation.
